import { signOut } from "next-auth/react";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import { connectToDatabase } from "../util/mongodb";
import Feed from "../components/Feed";


export default function Home({posts}) {
  //happening on the client side
  const router = useRouter();
  const { status } = useSession({
    required: true,
    onUnauthenticated() {
      // The user is not authenticated, handle it here.
      router.push("/home");
    },
  });

  return (
    <div className="bg-[#F3F2EF] dark:bg-black dark:text-white h-screen overflow-y-scroll md:space-y-6">
      <Head>
        <title>Feed | Linkedin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex justify-center gap-x-5 px-4 sm:px-12">
        <div className="flex flex-col md:flex-row gap-5">
          <Sidebar />
          <Feed />
          {/* <Feed posts={posts} /> */}
        </div>
        {/* <Widgets articles={articles} />
        <AnimatePresence>
          {modalOpen && (
            <Modal handleClose={() => setModalOpen(false)} type={modalType} />
          )}
        </AnimatePresence> */}
      </main>
      <div className="py-10 px-[100px]">
        <h1 className="py-5">HOME PAGE (APP STILL IN DEVELOPMENT)</h1>
        <button
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mt-40px rounded"
          onClick={signOut}
        >
          Sign Out
        </button>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  // Check if the user is authenticated on the server...
  const session = await getSession(context);
  console.log(session);
  if (!session) {
    return {
      redirect: {
        permanent: false,
        destination: "/home",
      },
    };
  }

  // Get posts on SSR
  // const { db } = await connectToDatabase();
  // const posts = await db
  //   .collection("posts")
  //   .find()
  //   .sort({ timestamp: -1 })
  //   .toArray();

  // // Get Google News API
  // const results = await fetch(
  //   `https://newsapi.org/v2/top-headlines?country=us&apiKey=${process.env.NEWS_API_KEY}`
  // ).then((res) => res.json());

  return {
    props: {
      session,
  //     articles: results.articles,
  //     posts: posts.map((post) => ({
  //       _id: post._id.toString(),
  //       input: post.input,
  //       photoUrl: post.photoUrl,
  //       username: post.username,
  //       email: post.email,
  //       userImg: post.userImg,
  //       createdAt: post.createdAt,
  //     })),
    },
  };
}
