import { signOut } from "next-auth/react";
import Head from "next/head";
import Header from "../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Linkedin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="py-10 px-[100px]">
        <h1 className="py-5">HOME PAGE (APP STILL IN DEVELOPMENT)</h1>
        <button
          class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mt-40px rounded"
          onClick={signOut}
        >
          Sign Out
        </button>
      </div>
    </>
  );
}
